version: '3.3'

services:
  prestashop:
    image: bitnami/prestashop:1.7
    environment:
      - PRESTASHOP_FIRST_NAME=${PRESTASHOP_FIRST_NAME}
      - PRESTASHOP_LAST_NAME=${PRESTASHOP_LAST_NAME}
      - PRESTASHOP_PASSWORD=${PRESTASHOP_PASSWORD}
      - PRESTASHOP_EMAIL=${PRESTASHOP_EMAIL}
      - PRESTASHOP_HOST=${PRESTASHOP_HOST}
      - PRESTASHOP_ENABLE_HTTPS=${PRESTASHOP_ENABLE_HTTPS}
      - PRESTASHOP_COUNTRY=${PRESTASHOP_COUNTRY}
      - PRESTASHOP_LANGUAGE=${PRESTASHOP_LANGUAGE}
      - PRESTASHOP_DATABASE_HOST=${PRESTASHOP_DATABASE_HOST}
      - PRESTASHOP_DATABASE_NAME=${MYSQL_DATABASE}
      - PRESTASHOP_DATABASE_USER=${MYSQL_USER}
      - PRESTASHOP_DATABASE_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    volumes:
      - prestashop_data:/bitnami/prestashop
    depends_on:
      - mariadb
    networks:
      - frontend_network
      - backend_network
  
  mariadb:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend_network
    security_opt:
      - seccomp:unconfined

  phpmyadmin:
    image: phpmyadmin:5
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
    networks:
      - frontend_network
      - backend_network

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    environment:
      #DOMAINS: 'localhost -> http://prestashop:80 #local'
      DOMAINS: 'practica16iaw.ddns.net -> http://prestashop:8080 #production'
    volumes:
      - ssl_certs_data:/var/lib/https-portal
    depends_on:
      - prestashop
    restart: always
    networks:
      - frontend_network

volumes:
  prestashop_data:
  mariadb_data:
  ssl_certs_data:

networks:
  frontend_network:
  backend_network:
